DELETE FROM [sysdba].[RESYNCTABLEDEFS]
WHERE [TABLENAME] = 'QUOTA'
GO
DELETE FROM [sysdba].[SECTABLEDEFS]
WHERE [TABLENAME] = 'QUOTA'
GO
DROP TABLE [sysdba].[QUOTA]
GO

DELETE FROM [sysdba].[RESYNCTABLEDEFS]
WHERE [TABLENAME] = 'FORECAST'
GO
DELETE FROM [sysdba].[SECTABLEDEFS]
WHERE [TABLENAME] = 'FORECAST'
GO
DROP TABLE [sysdba].[FORECAST]
GO

