//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesLogix.Jobs.Forecast.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesLogix.Jobs.Forecast.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Opportunities for {0}.
        /// </summary>
        internal static string Job_OpportunityRollover_Phase_ProcessingOpportunities {
            get {
                return ResourceManager.GetString("Job_OpportunityRollover_Phase_ProcessingOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Quota &amp; Forecast Users.
        /// </summary>
        internal static string Job_OpportunityRollover_Phase_Retrieving_Users {
            get {
                return ResourceManager.GetString("Job_OpportunityRollover_Phase_Retrieving_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Users processed.
        /// </summary>
        internal static string Job_OpportunityRollover_Results {
            get {
                return ResourceManager.GetString("Job_OpportunityRollover_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota &amp; Forecast Users.
        /// </summary>
        internal static string Job_OpportunityRollover_RoleName {
            get {
                return ResourceManager.GetString("Job_OpportunityRollover_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Job_Phase_Detail_Completed {
            get {
                return ResourceManager.GetString("Job_Phase_Detail_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing.
        /// </summary>
        internal static string Job_Phase_Detail_Finalizing {
            get {
                return ResourceManager.GetString("Job_Phase_Detail_Finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string Job_Phase_Detail_Initializing {
            get {
                return ResourceManager.GetString("Job_Phase_Detail_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Forecasts.
        /// </summary>
        internal static string Job_SnapshotForecasts_Phase_Retrieving {
            get {
                return ResourceManager.GetString("Job_SnapshotForecasts_Phase_Retrieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking Forecast Snapshots.
        /// </summary>
        internal static string Job_SnapshotForecasts_Phase_TakingSnapshots {
            get {
                return ResourceManager.GetString("Job_SnapshotForecasts_Phase_TakingSnapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Forecasts processed.
        /// </summary>
        internal static string Job_SnapshotForecasts_Results {
            get {
                return ResourceManager.GetString("Job_SnapshotForecasts_Results", resourceCulture);
            }
        }
    }
}
